config/routes.rb
Rails.application.routes.draw do
  get '/welcome/:first_name', to: 'dynamic_pages#user'
  get '/home', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/gossipinfo/:id', to: 'dynamic_pages#gossip', as: 'gossip_info'
  get '/userinfo/:id', to: 'dynamic_pages#user_page', as: 'user_info'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :tags, through: :gossips_tags
end

app/models/gossips_tag.rb
class GossipsTag < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, optional: true
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "CreatePrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "CreatePrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  def welcome
  end

  def self.username(id)
    username = (User.find(Gossip.find(id).user_id).first_name)  + " " + (User.find(Gossip.find(id).user_id).last_name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dynamic_pages/gossip.html.erb
 <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <div class="divider-custom divider-light">
                </div>
                <h2 class="page-section-heading text-center text-uppercase text-white">Gossip <%= params['id'] %></h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                </div>
                <!-- About Section Content-->
                <div>
                <p class="lead text-center"><%= Gossip.find(params['id']).content %></p>
                </div>
                <!-- About Section Button-->
                <div class="text-center mt-4">
                    <a <%= link_to (DynamicPagesController.username(params['id'])), user_info_path(Gossip.find(params['id']).user_id), :class =>"btn btn-xl btn-outline-light" %>
                </div>
            </div>
        </section>
</html>

app/views/dynamic_pages/user.html.erb
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Salut <%= params['first_name'] %></h1>
        </header>
</html>

app/views/dynamic_pages/user_page.html.erb
      <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="assets/images/avataaars.svg" alt="" />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0"><%= User.find(params['id']).first_name + " " + User.find(params['id']).last_name %></h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0"><%= Gossip.all.count {|gossip| gossip.user_id == params['id'].to_i} %> gossips posted</p>
                <p class="masthead-subheading font-weight-light mb-0"><%= User.find(params['id']).age %> years old</p>
                <p class="masthead-subheading font-weight-light mb-0"><%= City.find(User.find(params['id']).city_id).name %></p>            
                </div>
        </header>
    </body>
    <% Gossip.all.each do |gossip| %>
        <% if gossip.user_id == params['id'].to_i %>
            <p></p>
            </div>
                </div>
                <div class="container">
                <a> </a>
                    <div class="card text-center">
                        <div class="card-header"> Gossip <%=gossip.id %><br/></div>
                            <div class="card-body">
                                <h5 class="card-title"><%= User.find(gossip.user_id).first_name + " " + User.find(gossip.user_id).last_name %></h5>
                                <p class="card-text"><%= gossip.content %><br/></p>
                                <a <%= link_to "Learn more", gossip_info_path(gossip.id), :class =>"btn btn-primary"%></a>
                            </div>
                        </div>
                    <p></p>
                    </div>
                </div>
                <h1></h1>
            </div>
        <% end %>
    <% end %>
    </body>
</html>

app/views/dynamic_pages/welcome.html.erb
<h1>DynamicPages#welcome</h1>
<p>Find me in app/views/dynamic_pages/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjectRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Contact Us</title>
        <!-- Favicon-->
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
            <a <%= link_to "The Gossip Project", home_path, :class =>"navbar-brand js-scroll-trigger" %>

                <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a <%= link_to "Home", home_path, :class =>"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
                    <li class="nav-item mx-0 mx-lg-1"><a <%= link_to "Contact", contact_path, :class =>"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
                    <li class="nav-item mx-0 mx-lg-1"><a <%= link_to "Our Team", team_path, :class =>"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
                    </ul>
                </div>
            </div>
        </nav>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
        <!-- Masthead-->
        <header class="page-section-heading text-center text-uppercase text-secondary mb-0">>
        <header class="page-section-heading text-center text-uppercase text-secondary mb-0">>
        <header class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Us>
            <div class="container d-flex align-items-center flex-column">
            </div>
        </header>
    <body id="page-top">
        <!-- Contact Section-->
        <section class="page-section" id="contact">
            <div class="container">
                <!-- Contact Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Us</h2>
                <div> <p> </p> </div>
                <div> <p> </p> </div>
                <div> <p> </p> </div>
                <!-- Contact Section Form-->
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.-->
                        <form id="contactForm" name="sentMessage" novalidate="novalidate">
                            <div class="control-group">
                                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                    <label>Name</label>
                                    <input class="form-control" id="name" type="text" placeholder="Name" required="required" data-validation-required-message="Please enter your name." />
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="control-group">
                                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                    <label>Email Address</label>
                                    <input class="form-control" id="email" type="email" placeholder="Email Address" required="required" data-validation-required-message="Please enter your email address." />
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="control-group">
                                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                    <label>Phone Number</label>
                                    <input class="form-control" id="phone" type="tel" placeholder="Phone Number" required="required" data-validation-required-message="Please enter your phone number." />
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="control-group">
                                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                                    <label>Message</label>
                                    <textarea class="form-control" id="message" rows="5" placeholder="Message" required="required" data-validation-required-message="Please enter a message."></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <br />
                            <div id="success"></div>
                            <div class="form-group"><button class="btn btn-primary btn-xl" id="sendMessageButton" type="submit">Send</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

app/views/static_pages/home.html.erb
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">Welcome to TGP</h1>
            <div class="text-center mt-4">
                    <a class="btn btn-xl btn-outline-light">
                        Add a gossip !
                    </a>
                </div>
            <div class="container d-flex align-items-center flex-column">
            </div>
        </header>
    <body id="page-top">
    <body>
    <% Gossip.all.each do |gossip| %>
        <p></p>
        </div>
            </div>
            <div class="container">
            <a> </a>
                <div class="card text-center">
                    <div class="card-header"> Gossip <%=gossip.id %><br/></div>
                        <div class="card-body">
                            <h5 class="card-title"><%= User.find(gossip.user_id).first_name + " " + User.find(gossip.user_id).last_name %></h5>
                            <p class="card-text"><%= gossip.content %><br/></p>
                            <a <%= link_to "Learn more", gossip_info_path(gossip.id), :class =>"btn btn-primary"%></a>
                        </div>
                    </div>
                <p></p>
                </div>
            </div>
            <h1></h1>
        </div>
    <% end %>
    </body>
</html>

app/views/static_pages/team.html.erb
<!-- Masthead-->
    <header class="page-section-heading text-center text-uppercase text-secondary mb-0">>
    <header class="page-section-heading text-center text-uppercase text-secondary mb-0">>
    <header class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Us>
    <div class="container d-flex align-items-center flex-column"></div>
    </header>
    <body id="page-top">
        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="Our Team">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">Our Team</h2>
                <div> <p> </p> </div>
                <div> <p> </p> </div>
                <div> <p> </p> </div>
                <!-- About Section Content-->
                <!-- About Section Content-->
                <div class="row">
                    <div class="col-lg-12 ml-auto"><p class="lead">Hello, I made this project on my own. :)</p></div>
                </div>
            </div>
        </section>
    </body>
</html>